config/routes.rb
Rails.application.routes.draw do
  root 'calculations#index'
  resources :calculations, only: %i[show new create index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calculation.rb
class Calculation < ApplicationRecord
  def evaluate_string(input)
    values = []
    operators = []
    input = input.scan(/\w+|\W/)
    input.each_with_index do |token, index|
      if ((token != "*") && (token != "+") && (token != "-") && (token != "/"))
        input[index] = token.to_i
      end
    end
    input.each do |val|
      if val.class == Fixnum
        values << val
      elsif val.class == String
        if (val == '+' || val == '-') && (operators.last == '*')
          calc = 0
          calc = values[-2] * values[-1]
          values.pop
          values.pop
          values << calc
          operators.pop
          redo
        elsif (val == '+' || val == '-') && (operators.last == '/')
          calc = 0
          calc = values[-2] / values[-1]
          values.pop
          values.pop
          values << calc
          operators.pop
          redo
        elsif (val == '+' || val == '-') && (operators.last == '+')
          calc = 0
          calc = values[-2] + values[-1]
          values.pop
          values.pop
          values << calc
          operators.pop
          redo
        elsif (val == '+' || val == '-') && (operators.last == '-')
          calc = 0
          calc = values[-2] - values[-1]
          values.pop
          values.pop
          values << calc
          operators.pop
          redo
        else
          operators.push(val)
        end
      end
    end

    output = 0
    if values.length > 2
      output = values[-2].send(operators[-1], values[-1]) if !operators[-1].nil?
      output = output.send(operators[0], values[0]) if !operators[0].nil?
    else
      output = values[0].send(operators[0], values[1])
    end
    output
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/calculations_controller.rb
class CalculationsController < ApplicationController
  before_action :set_calculation, only: [:show, :edit, :update, :destroy]

  # GET /calculations
  # GET /calculations.json
  def index
    @calculations = Calculation.all
  end

  # GET /calculations/1
  # GET /calculations/1.json
  def show
  end

  # GET /calculations/new
  def new
    @calculation = Calculation.new
  end

  # POST /calculations
  # POST /calculations.json
  def create
    calculation_string = Calculation.new
    evaluation = calculation_string.evaluate_string(calculation_params[:expression])
    calculation_string.expression = calculation_params[:expression]
    calculation_string.evaluation = evaluation
    respond_to do |format|
      if calculation_string.save
        format.html { redirect_to calculation_string, notice: "Evaluated value of expression is #{evaluation}" }
        format.json { render :show, status: :created, location: @calculation }
      else
        format.html { render :new }
        format.json { render json: calculation_string, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calculations/1
  # PATCH/PUT /calculations/1.json
  def update
    respond_to do |format|
      if @calculation.update(calculation_params)
        format.html { redirect_to @calculation, notice: 'Calculation was successfully updated.' }
        format.json { render :show, status: :ok, location: @calculation }
      else
        format.html { render :edit }
        format.json { render json: @calculation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calculations/1
  # DELETE /calculations/1.json
  def destroy
    @calculation.destroy
    respond_to do |format|
      format.html { redirect_to calculations_url, notice: 'Calculation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calculation
      @calculation = Calculation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calculation_params
      params.require(:calculation).permit(:expression)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculations_helper.rb
module CalculationsHelper
end

app/views/calculations/_form.html.erb
<%= form_for(calculation) do |f| %>
  <% if calculation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(calculation.errors.count, "error") %> prohibited this calculation from being saved:</h2>

      <ul>
      <% calculation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :expression %>
    <%= f.text_field :expression %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calculations/index.html.erb
<h1>Evaluation Results</h1>
<table border="2">
  <thead>
    <tr>
      <th>Expression</th>
      <th>Evaluated Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @calculations.each do |calculation| %>
      <tr>
        <td><%= calculation.expression %></td>
        <td><%= calculation.evaluation %></td>        
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Calculation', new_calculation_path %>

app/views/calculations/new.html.erb
<h1>New Calculation</h1>

<%= render 'form', calculation: @calculation %>

<%= link_to 'Back', calculations_path %>

app/views/calculations/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Back', calculations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calculator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>